### PR TITLE
Revert "Adding the missing roc:: namespace"

### PR DESCRIPTION
**Pull request by wenkaidu**
Reverts ROCmSoftwarePlatform/rccl#570

### CODE REVIEW

**Review by saadrahim — APPROVED** [review]

**Comment by dmikushin** [comment]
Dear all, the PyTorch fix is being reviewed here: https://github.com/pytorch/pytorch/pull/80446 Could you please kindly help me to pass it through, such that #570 won't be breaking PyTorch. Thank you!

**Review by gilbertlee-amd — APPROVED** [review]

**Comment by dmikushin** [comment]
Hi @wenkaidu , as the required change has landed into PyTorch, could you please re-revert this? Thanks!

**Comment by wenkaidu** [comment]
> Hi @wenkaidu , as the required change has landed into PyTorch, could you please re-revert this? Thanks!

Mani checked yesterday and found the PyTorch commit is not yet in ROCm build

**Comment by dmikushin** [comment]
Hi @wenkaidu , could we please check again if it's now the right time to merge this PR?

**Comment by wenkaidu** [comment]
@dmikushin ROCm 5.3 branch still doesn't have your patch: https://github.com/ROCmSoftwarePlatform/pytorch/blob/rocm5.3_internal_testing/cmake/public/LoadHIP.cmake

**Pull request merged**
