### PR TITLE
Add RCCL primitive testing

### PR DESCRIPTION
**Pull request by wenkaidu**

### CODE REVIEW

**Comment by gilbertlee-amd** [comment]
Is there any way for us to include the "current" collective device code in use within the RCCL library instead of copy_kernel.h?

**Comment by wenkaidu** [comment]
The key function is copy exact from src/collectives/device/common_kernel.h:
__device__ inline void ReduceCopy128b( const int w, const int nw, const int t,
    Pack128 * src0, Pack128 * src1, Pack128 * dest0, Pack128 * dest1,
    const int N) {

**Comment by gilbertlee-amd** [comment]
> The key function is copy exact from src/collectives/device/common_kernel.h:
> device inline void ReduceCopy128b( const int w, const int nw, const int t,
> Pack128 * src0, Pack128 * src1, Pack128 * dest0, Pack128 * dest1,
> const int N) {

Yes - does this mean we can just include it, instead of making a copy?  That way if we change things, we don't need to synchronize with this one?

**Comment by wenkaidu** [comment]
Both approach has plus and minus. Current approach is a simple portable test utilities can be easily used anywhere. While common_kernel.h includes core.h and introduces too many dependencies. I would prefer keep it simple for now.

**Pull request merged**
