### PR TITLE
Reducing scope of linker flags to rccl target to avoid warnings

### PR DESCRIPTION
**Pull request by gilbertlee-amd**

### CODE REVIEW

**Comment by wenkaidu** [comment]
[100%] Built target googletest
CMake Warning (dev) at build/googletest-src/CMakeLists.txt:6 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
    PROJECT_VERSION_TWEAK
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by gilbertlee-amd** [comment]
> [100%] Built target googletest
> CMake Warning (dev) at build/googletest-src/CMakeLists.txt:6 (project):
> Policy CMP0048 is not set: project() command manages VERSION variables.
> Run "cmake --help-policy CMP0048" for policy details. Use the cmake_policy
> command to set the policy and suppress this warning.
> 
> The following variable(s) would be set to empty:
> 
> ```
> PROJECT_VERSION
> PROJECT_VERSION_MAJOR
> PROJECT_VERSION_MINOR
> PROJECT_VERSION_PATCH
> PROJECT_VERSION_TWEAK
> ```
> 
> This warning is for project developers. Use -Wno-dev to suppress it.

I've addressed this by switching to a tagged release of GoogleTest and changing necessary macros

**Comment by wenkaidu** [comment]
It still output some messages like below. Can this be removed as well?

[ 22%] Performing download step (git clone) for 'googletest'
Cloning into 'googletest-src'...
Note: checking out 'release-1.8.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 2fe3bd9... Merge pull request #1433 from dsacre/fix-clang-warnings

**Comment by gilbertlee-amd** [comment]
> It still output some messages like below. Can this be removed as well?
> 
> [ 22%] Performing download step (git clone) for 'googletest'
> Cloning into 'googletest-src'...
> Note: checking out 'release-1.8.1'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
> git checkout -b
> 
> HEAD is now at 2fe3bd9... Merge pull request #1433 from dsacre/fix-clang-warnings

In order to fix this, we will need to add GIT_CONFIG advice.detachedHead=false to the ExternalProject_Add call in test/CMakefile.txt.in, and also set the minimum required CMake version to 3.8.  I propose we revisit this after CMake 3.8 becomes more prevalent.

**Comment by wenkaidu** [comment]
LGTM

**Pull request merged**
