### PR TITLE
rccl-prim-test: auto-detect rings in 4P and 8P configurations

### PR DESCRIPTION
**Pull request by wenkaidu**

### CODE REVIEW

**Comment by wenkaidu** [comment]
This change is in test code only and is not built by CI.
The error was caused by same malloc issue.
/opt/rocm/llvm/lib/clang/11.0.0/include/cuda_wrappers/new:41:12: error: reference to __host__ function 'malloc' in __device__ function
  return ::malloc(size);

**Comment by saadrahim** [comment]
That was a hipclang issue for the failure.

**Comment by wenkaidu** [comment]
@saadrahim what's next step? create pull request to staging?

**Comment by saadrahim** [comment]
I have been fast forwarding other libraries that I work on. I think Nico does that as well. That is an open question. rocBLAS does PRs.

**Comment by wenkaidu** [comment]
sorry, I thought this was for the develop branch.

**Comment by wenkaidu** [comment]
I will have another pull request for develop branch to test the process

**Comment by saadrahim** [comment]
what usually happens is PRs for individual commits to master will cease as somepoint

**Pull request merged**
