### PR TITLE
Fix build with hip-clang.

### PR DESCRIPTION
**Pull request by mhbliao**
- Add necessary function attribute for HIP programming model.
- Explicitly include hsa headers.

### CODE REVIEW

**Comment by wenkaidu** [comment]
There are many places that use "defined(__HIP_PLATFORM_HCC__) || defined(__HCC__)". If __HIPCC __ is needed, can you replace them all?

**Comment by mhbliao** [comment]
done

> There are many places that use "defined(**HIP_PLATFORM_HCC**) || defined(**HCC**)". If __HIPCC __ is needed, can you replace them all?

**Comment by wenkaidu** [comment]
sorry I just merged another patch. there is a new "#if defined" in init.cc line #153. Can you rebase your patch and add HIPCC there as well?

**Comment by mhbliao** [comment]
done

> sorry I just merged another patch. there is a new "#if defined" in init.cc line #153. Can you rebase your patch and add HIPCC there as well?

**Comment by mhbliao** [comment]
The 2 CI failures seems irrelevant to this change. Could someone have a look?

Extracted from both of them

```
[100%] Linking CXX executable UnitTests

clang-9: error: ROCm agent detector could not identify any valid targets; please specify the target explicitly by passing a valid value to -amdgpu-target

clang-9: warning: -amdgpu-target argument 'gfx000' is not recognized; using gfx803 instead [-Winvalid-command-line-argument]

test/CMakeFiles/UnitTests.dir/build.make:309: recipe for target 'test/UnitTests' failed

make[2]: *** [test/UnitTests] Error 1

CMakeFiles/Makefile2:126: recipe for target 'test/CMakeFiles/UnitTests.dir/all' failed

make[1]: *** [test/CMakeFiles/UnitTests.dir/all] Error 2

Makefile:149: recipe for target 'all' failed

make: *** [all] Error 2

[Pipeline] }

[Pipeline] // timeout

[Pipeline] }
```
and
```
[100%] Linking CXX executable UnitTests

clang-9: error: ROCm agent detector could not identify any valid targets; please specify the target explicitly by passing a valid value to -amdgpu-target

clang-9: warning: -amdgpu-target argument 'gfx000' is not recognized; using gfx803 instead [-Winvalid-command-line-argument]

test/CMakeFiles/UnitTests.dir/build.make:309: recipe for target 'test/UnitTests' failed

make[2]: *** [test/UnitTests] Error 1

CMakeFiles/Makefile2:126: recipe for target 'test/CMakeFiles/UnitTests.dir/all' failed

make[1]: *** [test/CMakeFiles/UnitTests.dir/all] Error 2

Makefile:149: recipe for target 'all' failed

make: *** [all] Error 2

[Pipeline] }

[Pipeline] // timeout

[Pipeline] }
```

**Comment by wenkaidu** [comment]
CI server has been down for sometime.

**Pull request merged**
