### PR TITLE
Add allgather support

### PR DESCRIPTION
**Pull request by jeffdaily**
Tests included.

### CODE REVIEW

**Comment by jeffdaily** [comment]
@wenkaidu you didn't show up in the reviewer drop-down choices.  I started with your original PR commit, cherry-picked it, and added the missing tests.

**Comment by jeffdaily** [comment]
@wenkaidu found a typo in the rcclAllGather.cpp test.  The test is passing now.  @adityaatluri please review and let us know what you think.  Thanks.

**Comment by jeffdaily** [comment]
@adityaatluri I believe I have resolved all requests.  Please confirm.

**Comment by adityaatluri** [comment]
Before I merge it, let me check if https://github.com/ROCmSoftwarePlatform/rccl/pull/35 works.

**Comment by adityaatluri** [comment]
@jeffdaily can you re-run validation test for `__fp16`?

**Comment by jeffdaily** [comment]
I re-ran validation test for `__fp16` and it succeeded.  Good to go.

**Pull request merged**
