### PR TITLE
Updating RCCL Replayer README

### PR DESCRIPTION
**Pull request by gilbertlee-amd**
## Details
Provide more details about collecting logs to use with the RCCL replayer

**Work item:** None

**What were the changes?**  
Add two steps about collective logs and combining logs

**Why were the changes made?**  
To make it a better reference on how to use RCCL replayer

**How was the outcome achieved?**  

**Additional Documentation:**  

## Approval Checklist
___Do not approve until these items are satisfied.___
- [ ] Verify the CHANGELOG has been updated, if
  - there are any NCCL API version changes,
  - any changes impact library users, and/or
  - any changes impact any other ROCm library.

### CODE REVIEW

**Review by corey-derochie-amd — APPROVED** [review]
Should this also be cherry-picked into 6.3?

**Comment by amd-jnovotny** [comment]
@gilbertlee-amd : are there any sections in docs that needs to be updated?

**Comment by corey-derochie-amd** [comment]
> @gilbertlee-amd : are there any sections in docs that needs to be updated?

We have a number of tools in the repo, but none appear to be documented by docs/* , only in their own README. Should they be? I'm not sure if they are "shipped" because I don't think they're part of the package, just the repo.

**Comment by amd-jnovotny** [comment]
@corey-derochie-amd Thanks! Just wanted to make sure. I think we can leave this for now, but I'll soon take a look at the repo with an eye to what might need to be added to the docs.

**Comment by gilbertlee-amd** [comment]
I don't believe this needs to be cherry-picked.

**Pull request merged**
