### PR TITLE
Automatically add channels and select appropriate NIC through environ…

### PR DESCRIPTION
**Pull request by clearsky07**
Hello, I am a user of RCCL. When using RCCL, I found it inconvenient to increase the number of channels by parsing the GRAPH XML file. Therefore, I added an environment variable "RCCL_NCHANNELS" to automatically increase the number of channels. In addition, the added code also takes into account the selection of appropriate NIC. We first construct an array of NIC, with two properties for each element: id and used. "id" indicates the network card number, and "used" indicates the number of times the NIC has been used. We use quicksort to sort the NIC array, and then assign the first element to the corresponding position of the "graph.inter" array; after each assignment, we perform quicksort again and increment "used". This way, we can easily use the environment variable to specify the number of channels and maximize the use of NIC. Currently, this modification has only been made on version rccl-2.13.4.

I tested these two methods of increasing the number of channels (by parsing the XML file/environment variable) at different scales, and the results showed that the performance of these two methods is the same.

### CODE REVIEW

**Comment by clearsky07** [comment]
If you have any better suggestions, please feel free to propose them.

**Comment by gilbertlee-amd** [comment]
Hi @clearsky07 - Thank you for this PR.

Could you explain how this is different than the current NCCL_MIN_CHANNELS environment variable, or provide some examples of the generated graphs?

**Comment by clearsky07** [comment]
> Hi @clearsky07 - Thank you for this PR.
> 
> Could you explain how this is different than the current NCCL_MIN_CHANNELS environment variable, or provide some examples of the generated graphs?

Thank you for your reply. Sorry, I didn't think about NCCL_MIN_NCHANNELS before.So I ran another round of tests, comparing NCCL_MIN_NCHANNELS and RCCL_NCHANNELS.The results showed that RCCL_NCHANNELS had better performance.I have written my analysis and test results into the DOC document, you can view and analyze, so as to improve the network performance of RCCL.I sincerely hope that you can analyze my suggestions seriously and give your guidance.
[NCCL_MIN_NCHANNELS vs RCCL_NCHANNELS.docx](https://github.com/ROCmSoftwarePlatform/rccl/files/12213075/NCCL_MIN_NCHANNELS.vs.RCCL_NCHANNELS.docx)

**Comment by gilbertlee-amd** [comment]
Hi @clearsky07 - Sorry we were still in the process of analyzing your PR and testing it out.  Was there any particular reason why you closed the PR?

**Comment by clearsky07** [comment]
> Hi @clearsky07 - Sorry we were still in the process of analyzing your PR and testing it out. Was there any particular reason why you closed the PR?

I'm making some improvements and incorporating them into the environment variable NCCL_MIN_NCHANNELS. I'll create a new pull request in a few days.

**Pull request closed without merging**
